baseURL = 'https://tik9.github.io'
title = 'tiko'
theme = "ananke"

publishDir="docs"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

  [languages.en]
    title = "CV"
    languageName = "English"
    weight = 1

  [languages.de]
    title = "Lebenslauf"
    languageName = "German"
    weight = 2