name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " ${{ github.event_name }} event."
      - run: echo "${{ runner.os }} server hosted by GitHub!"
      - run: echo "branch is ${{ github.ref }} and ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "repo has been cloned to the runner."
      - name: List files in repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "${{ job.status }}."